### ISSUE TITLE
neonic date/time issues

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/GLRI_CEC_2016#26]
Repulled neonic data from NWIS. Found the following issues relative to the tracking form:

**In tracking but not in NWIS:**

- ~~all samples from Indiana Harbor Canal, site 04092750.~~ Now in NWIS, but missing sample from 016-08-02 (see comments below)

- ~~Maumee, site 04193500 on date 2016-05-10~~

- Genesee River, site 04193500 on date 2016-09-06

**In NWIS but not in tracking:**

- ~~Maumee, site 04193500 on date 2016-05-03 _guessing this is missing data above, should change date to reconcile. Note tracking date appears to be off - published as 2016-05-03 in Hladik. However, will change neonic date instead of tracking date since pesticides and glyphosate don't appear to be off._~~

**Comment by limnoliver** [comment]
@malutz-usgs -- any insight here based on your help with the neonic data?

I switched over to pulling from NWIS because there were some date/time issues in the file that was given to us, and also for reproducible/data publication reasons we'd like to make the switch. However, it seems like there is some missing data (see above) that is reported in the Hladik paper. 

Based on my investigation above, 

1. Maumee was submitted with wrong date and can be sorted out.

2. I'm not sure what's going on with Genesee River sample. 

3. Is it possible that Indiana Harbor Canal got submitted to NWIS with a different (wrong) site number, or not at all? This is my guess since all dates are missing.

**Comment by malutz-usgs** [comment]
Yeah, I would support the approach of pulling data from NWIS.  There were quite a few issues with the dates/times in the file that I was working in (pre-journal article table/spreadsheet from Michelle Hladik), and NWIS should (theoretically) represent the final/worked-through header info for all these samples. 

Responding to each issue... 
1) The OH data person (Stephanie Kula) had a bunch of great information for me.  The Maumee is kind of a special site; if you look at the sampling schedule [here](https://docs.google.com/spreadsheets/d/1Vrae7LSChyEVPdvFvZ1Hcwpe0TGCJYrTP0tu8-Bezwo/edit?usp=sharing), you'll notice that there schedule has zero GLRI CEC pesticide samples slated for collection.  That's because this sample was also being sampled for NAWQA for pesticides, and we saved some money here by not double sampling the site/just using the NAWQA pesticide data.  So, that's what's going on in the general sense.  Related to the sample that you asked about, according to the tracking sheet (and NWIS) the GLRI CEC sample on 5/3/2016 is at 1220 (that's the main sample; the 1225 sample on 5/3 is the neonic sample, and there do appear to be data here), but because of this agreement, the pesticide data are actually associated with the NAWQA sample which was given a time of 1200.  A full listing of the sites from that day:
 - 1200 (NAWQA) - where the pesticide data are
 - 1210 (GLRI Nutrients)
 - 1220 (GLRI CEC)
 - 1225 (GLRI CEC neonics)
 - 1201(NAWQA rep) - also has pesticide data
There were additional pesticides sampled for (by NAWQA again) on 5/10, but it seems like the sample that you really want is the one from 5/3.  Not sure if you're using recno's but if it's helpful, the recno for the NAWQA regular sample is 01601026, and the NAWQA rep is 01600179. 
Generally speaking, you can decipher which project each sample was collected for by checking out the  QW_PROJECT_CD field:
 - NAWQA is G1ESW00
 - GLRI Nutrients is FX456
 - GLRI CEC is FX412
Does that answer your question?

2) In your intial question/comment above, you give the wrong site number for the Genesee River, it should be 04231600.  The number you have there is for the Maumee.  I looked at samples from 9/2016 at 04231600 in the NWIS reporting tool and on NWIS web, and it looks like the header for both the main sample (9/6/2016 1730) and the neonic sample (9/6/2016 1735) are in there.  The neonic sample record doesn't have any data associated with it, which is a different issue...and maybe what you were talking about with your comment?  The file (from Michelle) that I worked with to suss out the header info for the neonic samples had some data in it...I didn't use the data at all and the data weren't loaded from it, but this sample didn't have any data available for this sample (aside from a single value for imidacloprid-d4 (surrogate % recovery))...I could follow up with the lab if the lack of data for this sample is unexpected/in question. It seems weird that they would want a sample header made if they didn't have any data for it... 

3) The Indiana batch file fell through the cracks.  I reached out to them last week, and they loaded it.  I have pulled the data down using the NWIS reporting tool, and everything looks okay in the header, but definitely let me know if you see any issues as you start digging deeper.  I would have expected that they would have had some 'bad QW' records hanging out from records that wouldn't load from the Hladik lab.  I sent an email to see if those are still around/if they can be loaded, but don't expect to hear back til Friday. If the data aren't hanging out in bad QW I'll request that the lab resend them.

**Comment by limnoliver** [comment]
Thanks @malutz-usgs! After some more investigation:

1. Yes, I've heard various bits and pieces about Maumee and why it's weird through the glyphosate and pesticide issues as well. I have neonic data from Maumee on 5/3, but not on 5/10. I noticed that the tracking sheet says 5/3, but once I pull in the tracking into R it says 5/10. In the original import code Laura wrote, there's a bunch of lines to clean up the tracking form, and one of those is to change that date from 5/3 to 5/10. I'm not sure why this is -- but now I know it's _not_ a data/NWIS issue but a processing issue. So - (I think) we can call this completed!

2. Sorry for the original site mistake - copy and paste error! No idea on this one -- from what I can tell, there should be a sample but there is not. 

3. Cool - will let you know if I find any issues. I just repulled from NWIS and it is not there yet - guessing there is some processing time?

**Comment by malutz-usgs** [comment]
1.  Ah, that makes sense.  I remember talking to Laura way back when about some of the updates/corrections she was making when pulling data into R. It sounds like this one is compeleted. Nice! 

2.  I'm a little confused. The way that we enter data into the QW database there are kind of two pieces to any sample record--there's the header (STAID, date, time, medium, etc.) and then the actual data (e.g., neonic lab data) that gets loaded later. I'm guessing since I was able to find the header, that you're wondering why there's no lab data associated with the header...am I reading that right?  I can reach out to Michelle if you like to try and get more info. Would that be helpful?

3.  There isn't much processing time.  I just looked back at my email to Stephanie the other day and I did ask about whether those data were still around somewhere and could be loaded.  I'll let you know what I hear back. My guess is that these data fell through the cracks...because if they hadn't it would have been a flag to them that they were missing sample headers, and they might have put two and two together and loaded my batch file.  Anyway, I'll wait to hear back from Stephanie, but I suspect we'll need to request that the lab resubmit data to IN. I would expect once they resend it would show up in the database quickly.

**Comment by malutz-usgs** [comment]
One more quick thing.  I have this lingering note rattling around in the back of my head related to the clean up stuff that Laura was doing to the tracking form.  It's probably irrelevant now, but just in case... 

Way back in October Michelle incorrectly changed the site associated with one of our records in the tracking form, and I changed it back about 3 weeks later.  I never knew if that affected Laura's clean up scripts or not. Regardless, it's for the first record in the WI sheet of the tracking form: Michelle had changed it to Manitowoc River/04085427 but it should have been (and I changed it back to) Milwaukee River/04087170 (this is for recno 01600010). 

Anyway, not sure if this helps answer any of the other questions you've had or if it's totally irrelevant, but thought I'd let you know.

**Comment by limnoliver** [comment]
Thanks for these notes, @malutz-usgs. I will keep those weird siteID issues in mind... Some updates on the above mentioned issues: 

1.  Completed

2. Yes, it would be helpful to reach out to Michelle H. RE missing Genesee River sample. Every indication is that the data _should_ be in NWIS but are not.

3. Indiana Harbor Canal (04092750) is now on NWIS! However, from the tracking form it appears there should be neonics measured on 2016-08-02 but they are not showing up in the pull from NWIS. 

We're getting so close!!

**Comment by malutz-usgs** [comment]
Following up...
2. I just sent her an email and cc'd you. 

3. Glad those are coming through!  Stephanie loaded the headers last week, and the data yesterday.  The 8/2/16 sample is a known issue; there's a time issue in the database and between the header and data files.  I think we have that figured out, but I'll need Stephanie to make the change and I think she might be back out in the field the rest of this week (not sure...). I'd anticipate she'll resolve that quickly when she's back in the office next week. I'll let you know when she's made the updates to the database.

**Comment by limnoliver** [comment]
Great -- the pesticide data (from schedule 2437) are also missing from IHC on 8/2 -- so hopefully the above fix will for neonics will also fix that issue!

**Comment by malutz-usgs** [comment]
That's interesting.  I'm not sure what's going on there.  I'm able to see the pesticide data on NWISweb [https://nwis.waterdata.usgs.gov/nwis/qwdata?search_site_no=04092750&search_site_no_match_type=exact&group_key=NONE&sitefile_output_format=html_table&column_name=agency_cd&column_name=site_no&column_name=station_nm&inventory_output=0&rdb_inventory_output=file&begin_date=2016-08-02&end_date=2016-08-02&TZoutput=0&pm_cd_compare=Greater%20than&radio_parm_cds=all_parm_cds&format=html_table&qw_attributes=0&qw_sample_wide=wide&rdb_qw_attributes=0&date_format=YYYY-MM-DD&rdb_compression=file&list_of_search_criteria=search_site_no](url)  The fact that there were two records holding pesticide data for that day is part of the issue that Stephanie and I are resolving with the Indiana database...

**Comment by limnoliver** [comment]
Hmm sorry just reran code and you're right - it's there, and it's in there twice. So hopefully the _duplicate_ issue gets resolved :)

**Comment by malutz-usgs** [comment]
Oh good, glad to hear it!  Yes, we'll resolve the duplicate issue as part of these changes.

**Comment by malutz-usgs** [comment]
I got a note from Stephanie that she's in and working on the IN issue.  She's going to delete the 1330 record entirely, so there will be a 1300 record and a 1305 record (for pesticides and neonics, respectively).  She'll change the time in the neonic data file (to be 1305) from the lab and upload it to the database.  I expect that will be done in the next couple hours.

**Comment by limnoliver** [comment]
Great - thanks for the update!

**Comment by malutz-usgs** [comment]
The updates to the IHC sample on 8/2/2016 are done.  Looks like things are showing up properly...[here](https://nwis.waterdata.usgs.gov/nwis/qwdata?search_site_no=04092750&search_site_no_match_type=exact&group_key=NONE&sitefile_output_format=html_table&column_name=agency_cd&column_name=site_no&column_name=station_nm&inventory_output=0&rdb_inventory_output=file&begin_date=2016-08-02&end_date=2016-08-02&TZoutput=0&pm_cd_compare=Greater%20than&radio_parm_cds=all_parm_cds&format=html_table&qw_attributes=0&qw_sample_wide=wide&rdb_qw_attributes=0&date_format=YYYY-MM-DD&rdb_compression=file&list_of_search_criteria=search_site_no) Let me know if you see other issues, otherwise I'll assume this one's resolved.

**Comment by malutz-usgs** [comment]
The recent reload to the database in NY (by Corey and Peggy) appears to have resolved the issue related to the 9/6/2016 sample at Genesee River.  See [here](https://nwis.waterdata.usgs.gov/nwis/qwdata?search_site_no=04231600&search_site_no_match_type=exact&group_key=NONE&sitefile_output_format=html_table&column_name=agency_cd&column_name=site_no&column_name=station_nm&inventory_output=0&rdb_inventory_output=file&begin_date=2016-09-06&end_date=2016-09-06&TZoutput=0&pm_cd_compare=Greater%20than&radio_parm_cds=all_parm_cds&format=html_table&qw_attributes=0&qw_sample_wide=wide&rdb_qw_attributes=0&date_format=YYYY-MM-DD&rdb_compression=file&list_of_search_criteria=search_site_no)  I think that resolves all the issues outlined on this thread, but let me know if you disagree.

**Comment by limnoliver** [comment]
Woohoo! Just repulled from NWIS and confirmed all of these issues are resolved. Thanks @malutz-usgs!
